# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8104ef0355493b2e7ecc388e1c2d6b095aa392eaa9e7dec0c6bff292839e4a9765cff83984e3dd56b55582f660dd61697152437f6cc2fe7c5184be8a0201d20

test:
  secret_key_base: 4c3a958fa6807d43e0d7fdfceb53c07a9e0b4f0c0414eabb290f5a200947a7bc563bfea1442d906a03b7786cd51e4e9ab5ad76c0db13194bc7fd0fc48d5da62a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
